import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topbar from "./components/topbar";
import dynamic from "next/dynamic";

// Cargar dinámicamente BokehBackground con SSR desactivado
const BokehBackground = dynamic(() => import("./components/blackhole"), {
  ssr: false,
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Topbar />
        {children}
        <div className="absolute -z-10 w-full h-[100dvh] left-0 top-0 backdrop-blur-md"></div>
        <BokehBackground /> {/* Aquí colocas el background */}
      </body>
    </html>
  );
}
